# Generated by Django 5.2.1 on 2025-05-10 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('student', 'Estudiante'), ('instructor', 'Instructor')], default='student', max_length=10, null=True),
        ),
    ]
