# Generated by Django 5.2.1 on 2025-05-10 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Visible para estudiantes')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadatos adicionales')),
                ('duration_minutes', models.PositiveIntegerField(default=0, help_text='Tiempo estimado para completar este contenido', verbose_name='Duración estimada (minutos)')),
                ('is_mandatory', models.BooleanField(default=True, help_text='Indica si este contenido es esencial para la sesión', verbose_name='Es obligatorio')),
                ('available_from', models.DateTimeField(blank=True, help_text='Fecha a partir de la cual este contenido estará disponible', null=True, verbose_name='Disponible desde')),
                ('available_until', models.DateTimeField(blank=True, help_text='Fecha hasta la cual este contenido estará disponible', null=True, verbose_name='Disponible hasta')),
                ('tags', models.CharField(blank=True, help_text='Etiquetas separadas por comas para categorizar el contenido', max_length=255, verbose_name='Etiquetas')),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Principiante'), ('intermediate', 'Intermedio'), ('advanced', 'Avanzado')], default='beginner', max_length=20, verbose_name='Nivel de dificultad')),
                ('is_evaluable', models.BooleanField(default=False, help_text='Indica si este contenido contribuye a la evaluación', verbose_name='Es evaluable')),
                ('video_url', models.URLField(help_text='URL del video (YouTube, Vimeo, etc.)', verbose_name='URL del video')),
                ('duration', models.PositiveIntegerField(default=0, help_text='Duración del video en segundos', verbose_name='Duración (segundos)')),
                ('transcript', models.TextField(blank=True, help_text='Transcripción textual del contenido del video', verbose_name='Transcripción')),
                ('slides_url', models.URLField(blank=True, help_text='URL de las diapositivas utilizadas en el video (Google Slides, PDF, etc.)', verbose_name='URL de diapositivas')),
                ('is_external', models.BooleanField(default=True, help_text='Indica si el video está alojado en una plataforma externa o en el servidor', verbose_name='Video externo')),
                ('thumbnail', models.ImageField(blank=True, help_text='Imagen de vista previa del video', null=True, upload_to='video_thumbnails/', verbose_name='Miniatura')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contents', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='courses.session', verbose_name='Sesión')),
            ],
            options={
                'verbose_name': 'Video Clase',
                'verbose_name_plural': 'Video Clases',
                'ordering': ['session', 'order'],
            },
        ),
    ]
