# Generated by Django 5.2.1 on 2025-05-22 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_reading', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeblock',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('html', 'HTML'), ('css', 'CSS'), ('sql', 'SQL'), ('bash', 'Bash/Shell'), ('json', 'JSON'), ('xml', 'XML'), ('yaml', 'YAML'), ('markdown', 'Markdown'), ('django-template', 'Django Template'), ('text', 'Texto plano')], default='text', max_length=50, verbose_name='Lenguaje'),
        ),
    ]
